version: 0.0
os: linux 
files:
  - source: /
    destination: /usr/src/scattergories
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      runas: root
    - location: /scripts/build.sh
      runas: root
  ApplicationStart:
    - location: /scripts/start.sh
      runas: root
