version: 0.0
os: linux 
files:
  - source: /
    destination: /usr/src/scattergories
hooks:
  PreInstall:
    - location: /scripts/cleanup.sh
      runas: root
  ApplicationStart:
    - location: /scripts/codedeploy.sh
      runas: root